project_name: apid

before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    binary: apid
    ldflags:
      - "-w"
      - "-s"
      - "-X github.com/getapid/apid/cmd.version={{ .Version }}"
    goos:
      - linux
      - openbsd
      - solaris
      - freebsd
      - darwin
      - windows
    goarch: ["386", "amd64", "arm", "arm64"]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc

archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"
    format: binary

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - apid

    image_templates:
      - "ghcr.io/getapid/apid:{{ .Version }}"
      - "ghcr.io/getapid/apid:latest"

    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

    dockerfile: dockerfile
