project_name: apid

before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    binary: apid
    ldflags:
      - "-w"
      - "-s"
      - "-X github.com/getapid/apid/cmd.version={{ .Version }}"
    goos:
      - linux
      - openbsd
      - solaris
      - freebsd
      - darwin
      - windows
    goarch: ["386", "amd64", "arm", "arm64"]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - apid

    image_templates:
      - "getapid/apid:latest"
      - "getapid/apid:{{ .Version }}"
    dockerfile: dockerfile
