project_name: apid

before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    binary: apid
    ldflags:
      - "-w"
      - "-s"
      - "-X github.com/getapid/apid/cmd.version={{ .Version }}"
    goos:
      - linux
      - openbsd
      - solaris
      - freebsd
      - darwin
      - windows
    goarch: ["386", "amd64", "arm", "arm64"]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc

archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"
    format: binary

dockers:
  - image_templates: ["ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/getapid/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/getapid/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=GNU
  - image_templates: ["ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/getapid/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/getapid/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=GNU

docker_manifests:
  - name_template: ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}
    image_templates:
    - ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}-amd64
    - ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/getapid/{{ .ProjectName }}:latest
    image_templates:
    - ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}-amd64
    - ghcr.io/getapid/{{ .ProjectName }}:{{ .Version }}-arm64v8