name: CI
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release-cli:
    name: Release cli
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Go Test
        run: |
          make test/ci

      - name: Release CLI executables
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          DOCKER_HUB_USERNAME: getapid
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
          docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          PATH=$PATH:./bin/ make release
