name: Release cli
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release-cli:
    name: Release cli
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get Go dependencies
      run: |
        go get github.com/golang/mock/mockgen

    - name: Go Test
      run: |
        make test

    - name: End to end tests
      run: |
        make build-e2e e2e

    - name: Release CLI executables
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        DOCKER_HUB_USERNAME: getapid
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
        docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
        PATH=$PATH:./bin/ make release
