name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build-cli:
    name: Build cli
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get Go dependencies
      run: |
        go get github.com/golang/mock/mockgen

    - name: Go Test
      run: |
        make test

    - name: End to end tests
      run: |
        make build-e2e e2e

    - name: Build CLI executables
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        DOCKER_HUB_USERNAME: getapid
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
        make release

    - name: Set up zola 0.9.0
      run: |
        wget -q -O - "https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xzf - -C /usr/local/bin

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Build static site
      env:
        CLICOLOR: 0
      run: |
        cd site
        npm i
        zola build --base-url https://getapid.com

    - name: Set up s3cmd 2.0.1
      run: |
        sudo apt install s3cmd

    - name: Publish static site
      env:
        SITE_NAME: unruffled-franklin-e163c9
        NETLIFY_PERSONAL_TOKEN: ${{ secrets.NETLIFY_PERSONAL_TOKEN }}
      run: |
        cd site
        zip -r site.zip public
        curl -H "Content-Type: application/zip" \
          -H "Authorization: Bearer ${NETLIFY_PERSONAL_TOKEN}" \
          --data-binary "@site.zip" \
          https://api.netlify.com/api/v1/sites/${SITE_NAME}.netlify.com/deploys

    - name: Update sitemaps
      run: |
        curl https://www.google.com/webmasters/sitemaps/ping?sitemap=https://www.getapid.com/sitemap.xml || true
        curl https://www.bing.com/ping?sitemap=https://www.getapid.com/sitemap.xml || true
